---
- name: "apache instalation using docker"
  hosts: prod
  become: true
  pre_tasks:
  - name: install epel repo
    package: name=epel-release state=present
    when: ansible_distribution == "CentOS"
  - name: install python-pip
    yum: name=python3-pip state=present update_cache=yes
  - name: install wget and git
    yum:
      name: "{{ item }}"
      state: present   
    loop:
      - git
      - wget      
  - name: install docker python
    pip: name=docker-py
    vars: 
      ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: "Creation of a directory"
    file:
      path: "/var/www"
  - name: html file generation
    template:
      src: "templates/index.html.j2"
      dest: "/var/www/index.html"
  - name: create apache container
    docker_container:
      name: webapp
      image: httpd
      ports:
        - "80:80"
      volumes: 
        - /var/www:/usr/local/apache2/htdocs
    vars: 
      ansible_python_interpreter: /usr/bin/python3