---
- name: "apache instalation using docker"
  hosts: prod
  pre_tasks:
  - name: install docker python
    pip: name=docker-py
  tasks:
  - name: create apache container
    docker_container:
      name: webapp
      image: httpd
      ports:
        - "80:80"