---
- name: "install wordpress"
  hosts: prod
  become: true
  vars:
    system_user: admin
  pre_tasks:
  - name: create www-data user
    user: 
      name: www-data
      state: present
  roles:
  